### ISSUE TITLE
warning: Enum.chunk/4 is deprecated. Use Enum.chunk_every/4 instead

### ISSUE THREAD

**Issue by Francisco-Castro** [codedge-llc/pane#1]
Deprecated function.

warning: Enum.chunk/4 is deprecated. Use Enum.chunk_every/4 instead

https://github.com/codedge-llc/pane/blob/e10e80383015773d7c17f2436e5a280d717bdd30/lib/page.ex#L44

**Comment by hpopp** [comment]
Totally got left off my radar for a while but thanks for the heads up! Fixed in #2 and published as `v0.4.0`.
